// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: '1:245228608969:web:your-web-app-id',
    messagingSenderId: '245228608969',
    projectId: 'gold-gateway-397319',
    authDomain: 'gold-gateway-397319.firebaseapp.com',
    storageBucket: 'gold-gateway-397319.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzsWIzS2MrAWkz9KDFRaMmqlNqn4xSwps',
    appId: '1:245228608969:android:3728606c3f555c70ef1c18',
    messagingSenderId: '245228608969',
    projectId: 'gold-gateway-397319',
    storageBucket: 'gold-gateway-397319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:245228608969:ios:your-ios-app-id',
    messagingSenderId: '245228608969',
    projectId: 'gold-gateway-397319',
    storageBucket: 'gold-gateway-397319.firebasestorage.app',
    iosBundleId: 'com.law_link.TSAR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:245228608969:macos:your-macos-app-id',
    messagingSenderId: '245228608969',
    projectId: 'gold-gateway-397319',
    storageBucket: 'gold-gateway-397319.firebasestorage.app',
    iosBundleId: 'com.law_link.TSAR',
  );
}
